### ISSUE TITLE
Update postgres path to ensure 9.5 version

### ISSUE THREAD

**Issue by Jesus89** [gfiorav/carto_loves_mac#13]
I have updated the alias paths to avoid conflicts with other versions, in my case 9.6

```
alias start_postgres='pg_ctl -D /usr/local/var/postgresql\@9.5 -l /usr/local/var/postgres/server.log start'
alias stop_postgres='pg_ctl -D /usr/local/var/postgresql\@9.5 -l /usr/local/var/postgres/server.log stop'
```

**Comment by gfiorav** [comment]
Hey!

Thanks for opening this issue.

If I understand correctly, instead of creating a symlink to generic `/usr/local/var/postgresql`, you propose to fix this at aliasing level.

Fair enough, but what does `pg_config` point to? Whatever is outputted by that command will determine how every piece that needs PSQL will behave (where extensions will be installed, what PSQL different pieces will use).

Having a sound path for `pg_config` to be right is the hardest part of having multiple PSQL installations IMHO. `which pg_config` or reading the `pg_config` will tell you what version it will point to.

I'd prefer to leave this guide on the premise of only one version installed, since this is the CARTO recommended case and more "beginner friendly". For that, I think the symlink works best.

Thanks anyway!
